# Generated by Django 4.1.4 on 2023-05-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequestlog',
            options={'verbose_name': 'API Request logs'},
        ),
    ]
